# Generated by Django 4.1.4 on 2022-12-30 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_movie_author_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentAndStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, help_text="텍스트", max_length=255, null=True
                    ),
                ),
                ("star_cnt", models.IntegerField(blank=True, default=3, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blog_idx",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.blog",
                    ),
                ),
            ],
        ),
    ]
