# Generated by Django 4.1.4 on 2023-01-14 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_blog_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentandstar",
            name="movie",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="game.movie"
            ),
        ),
    ]
